version: '2.1'

services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "16500:16500"
    environment:
      ES_CONNECT_RETRY: 120
    volumes:
      - elk:/var/lib/elasticsearch
      - ./02-tcp-input.conf:/etc/logstash/conf.d/02-tcp-input.conf
      - ./30-output.conf:/etc/logstash/conf.d/30-output.conf
    networks:
      - elknet
  tcp-proxy:
    image: tecnativa/tcp-proxy
    ports:
      - "16600:16600"
    environment:
      LISTEN: ":16600"
      TALK: "elk:16500"
      TIMEOUT_CLIENT: 10
      TIMEOUT_CLIENT_FIN: 5
    networks:
      - elknet

volumes:
  elk:

networks:
  elknet:
    driver: bridge
    ipam:
      driver: default
